### ISSUE TITLE
Don't use SDL_GetWindowSurface in combination with Rendering API

### ISSUE THREAD

**Issue by blackwolf12333** [alexdantas/sdl2-platformer#1]
According to the SDL2 documentation you can't combine a call to SDL_GetWindowSurface with the rendering API. So you shouldn't use it in src/Window.cpp

I have no idea how to fix this however :(

**Comment by alexdantas** [comment]
Wow, congratulations for reporting the first issue of `sdl2-platformer`! :octocat: 

It's been a while since I touched SDL2 stuff but I kinda grasp what you meant. I guess at the time I did not have an idea on how to fix this too.

The problem is that I was converting my previous game engine that used SDL1.2. With that in mind it was hard to give up on the rendering API without changing considerably the code base.

Perhaps it should be better to learn SDL2 from scratch and remake the game engine from scratch. But of course that would take an incredible amount of time. :frowning: 

If you ever find any clues please report them here. It would be nice to know regardless :smiley:

**Comment by blackwolf12333** [comment]
I already thought it would require rewriting the whole thing because you can't use Surfaces anymore with that fancy new API. And you use them quite a lot I believe.
